### ISSUE TITLE
Extract Ruby bindings to confium-ruby (`confium` gem)

### ISSUE THREAD

**Issue by ronaldtse** [confium/confium#10]
Target repository: https://github.com/confium/confium-ruby

**Comment by maxirmx** [comment]
Do you mean 'move ruby gem code to new repository' ?

**Comment by ronaldtse** [comment]
Yes, the goal is to move the `confium-ruby` directory into the new repository. The issue to tackle is that we need to clone code from this repo in order to build/run the Ruby tests. Thanks!

**Comment by maxirmx** [comment]
@ronaldtse 
What is the plan for botan plugin, shall I keep it here or move confium-ruby ?

**Comment by ronaldtse** [comment]
Done in #15 . Thank you @maxirmx !
