### ISSUE TITLE
Publish Confium in crate

### ISSUE THREAD

**Issue by ronaldtse** [confium/confium#6]

**Comment by maxirmx** [comment]
@ronaldtse  
We need to have ${{ secrets.CARGO_REGISTRY_TOKEN }} in this repo.
Thank you

**Comment by ronaldtse** [comment]
@maxirmx added: 
<img width="256" alt="Screen Shot 2022-12-05 at 11 23 07 AM" src="https://user-images.githubusercontent.com/11865/205542646-1bbe5851-3012-42a6-ae72-04fd3aabfb0d.png">

**Comment by maxirmx** [comment]
Thank you, @ronaldtse 
One more thing - we need a license or a license file as described here: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
